name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 18.x
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 18.x
          cache-dependency-path: yarn.lock

      - name: Install Dependencies
        run: yarn

      - name: Create Release Pull Request
        uses: changesets/action@aba318e9165b45b7948c60273e0b72fce0a64eb9 # v1.4.7
        with:
          publish: yarn release
        env:
          # Token setup in consul-ui-services' account
          GITHUB_TOKEN: ${{ secrets.CONSUL_UI_SERVICES_GH_PAT_TOKEN }}
          # Token setup in consul-ui-services' account
          NPM_TOKEN: ${{ secrets.CONSUL_UI_SERVICES_NPM_PAT_TOKEN }}
