name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 18.x
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
        with:
          node-version: 18.x
          cache-dependency-path: yarn.lock

      - name: Install Dependencies
        run: yarn

      - name: Create Release Pull Request
        uses: changesets/action@f13b1baaa620fde937751f5d2c3572b9da32af23 # v1.4.5
        with:
          publish: yarn release
        env:
          # Token setup in consul-ui-services' account
          GITHUB_TOKEN: ${{ secrets.CONSUL_UI_SERVICES_GH_PAT_TOKEN }}
          # Token setup in consul-ui-services' account
          NPM_TOKEN: ${{ secrets.CONSUL_UI_SERVICES_NPM_PAT_TOKEN }}
