name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 16.x
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: 16.x
          cache-dependency-path: yarn.lock

      - name: Install Dependencies
        run: yarn

      - name: Create Release Pull Request
        uses: changesets/action@v1 # TSCCR: no entry for repository "changesets/action"
        with:
          publish: yarn release
        env:
          # Token setup in consul-ui-services' account
          GITHUB_TOKEN: ${{ secrets.CONSUL_UI_SERVICES_GH_PAT_TOKEN }}
          # Token setup in consul-ui-services' account
          NPM_TOKEN: ${{ secrets.CONSUL_UI_SERVICES_NPM_PAT_TOKEN }}
